config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/index'
  devise_for :users do
    get '/users/sign_out' => 'users/sessions#destroy', :method => :delete
    get '/users/sign_up' => 'users/registrations#new'
  end
  resources :events do
    resources :tickets
  end
  resources :categories
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :account_transactions 
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :account 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets
  belongs_to :user
  belongs_to :category
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
  has_one :account
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?


    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name admin])
      devise_parameter_sanitizer.permit(:account_update, keys: %i[name last_name email password current_password])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @events = @category.events
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @ticket = Ticket.new
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :number_of_tickets, :ticket_id, :date, :category_id, :description, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end 
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    if @ticket.save
      redirect_to event_ticket_path(@ticket)
    else
      render 'new'
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
  end

  def destroy
  end

  private

  def ticket_params
    params.require(:ticket).permit(:user_id, :event_id, :price, :number, :on_resell, :sold_originally, :sold_on_market_place)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to events_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/categories/index.html.slim
h1 categories
=link_to 'add category', new_category_path
br
br
-@categories.each do |category|
  =category.name
  br

app/views/categories/new.html.slim
= form_with scope: :category, url: categories_path, local: true do |form|
  - if @category.errors.any?
    #error_explanation
      h2
        = pluralize(@category.errors.count, "error")
        | prohibited this movie from being saved:
      ul
        - @category.errors.full_messages.each do |msg|
          li
            = msg

  p
    = form.label :name
    = form.text_field :name
    br

    = form.submit

app/views/categories/show.html.slim
h1 events for #{@category.name}

-@events.each do |event|
  =event.name
  br

app/views/events/index.html.slim
h1 events index
=link_to 'add an event', new_event_path
br
br

-@events.each do |event|
  =link_to event.name, event_path(event)
  br
  = event.description
  br
  = event.date.strftime("%b %-d %Y")
  br
  = event.number_of_tickets
  br

app/views/events/new.html.slim
h1 events create

= form_with scope: :event, url: events_path, local: true do |form|
  - if @event.errors.any?
    #error_explanation
      h2
        = pluralize(@event.errors.count, "error")
        | prohibited this event from being saved:
      ul
        - @event.errors.full_messages.each do |msg|
          li
            = msg

  p
    = form.label :name
    = form.text_field :name
    br

    = form.label :number_of_tickets
    = form.number_field :number_of_tickets
    br

    = form.label :Date_event_occurs
    = form.date_field :date
    br

    = form.label :Event_category
    = form.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true
    br

    = form.label :description
    = form.text_area :description
    br
    = form.hidden_field :user_id, :value => current_user.id
    br



    = form.submit

app/views/events/show.html.slim
h1 events show page


= @event.name
br
= @event.description
br
= @event.number_of_tickets
br
= @event.date.strftime("%b %-d %Y")
br
=link_to 'buy tickets', new_event_ticket_path(@event.id)

app/views/purchases/new.html.slim
h1 buy ticket


= form_with scope: :purchase, url: purchases_path, local: true do |form|
  - if @purchase.errors.any?
    #error_explanation
      h2
        = pluralize(@purchase.errors.count, "error")
        | prohibited this ticket from being saved:
      ul
        - @purchase.errors.full_messages.each do |msg|
          li
            = msg

  p
    = form.label :name
    = form.text_field :name
    br

    = form.submit

app/views/tickets/index.html.slim
h1 all tickets

-@tickets.each do |ticket|
  =ticket.event.name
  br
  br

app/views/tickets/new.html.slim
= form_with scope: :ticket, url: event_tickets_path, local: true do |form|
  - if @ticket.errors.any?
    #error_explanation
      h2
        = pluralize(@ticket.errors.count, "error")
        | prohibited this ticket from being saved:
      ul
        - @ticket.errors.full_messages.each do |msg|
          li
            = msg

  p
    = form.label :number_of_tickets
    = form.number_field :number
    br
    = form.label :price
    = form.number_field :price
    br
    = form.label :number
    = form.text_field :number
    br
    = form.hidden_field :user_id, :value => current_user.id
    br

    = form.label :buy_tickets

    = form.submit

app/views/tickets/show.html.slim
h1 test show